version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile.dev
    ports:
      - ${APP_PORT:-8000}:8000
    volumes:
      - /eshop/vendor
      - /eshop/public/bundles
      - .:/eshop
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eshop
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PMA_PORT:-8080}:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - db
