version: '3'
services:
  app:
    container_name: lambda-app
    build:
      context: .
      dockerfile: docker/dev/Dockerfile.dev
    ports:
      - ${APP_PORT:-8000}:8000
    volumes:
      - /eshop/vendor
      - /eshop/public/bundles
      - /eshop/var
      - .:/eshop
    restart: always
    depends_on:
      - db
  db:
    container_name: lambda-db
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=eshop
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db_data:/var/lib/mysql
    restart: always
  phpmyadmin:
    container_name: lambda-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PMA_PORT:-8080}:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - db
volumes:
  db_data: