version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile.prod
    ports:
      - 8000:80
    volumes:
      - /var/www/html/vendor
      - /var/www/html/public/bundles
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=eshop
      - MYSQL_ROOT_PASSWORD=root
